# Generated by Django 4.1.7 on 2023-03-13 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_previouswriting'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouswriting',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
