# Generated by Django 4.1.7 on 2023-03-13 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_previouswriting_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouswriting',
            name='article',
            field=models.TextField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
